version: "3"
services:
  spa-node-app:
    build:
      context: .
      dockerfile: spa.Dockerfile
    ports:
      - 9596:80

  # nginx-app:
  #   build: 
  #     context: .
  #     dockerfile: nginx.Dockerfile
  #   ports:
  #     - 9596:80